<template>
    <div :class="main_content_width" class="justify-center mx-auto">
        <div class="sm:px-3 md:px-4 xl:px-5">
            <div class="flex justify-between w-full">
                <div class="flex mt-2 space-x-3">
                    <img
                        :src="company.logo"
                        alt="company logo"
                        class="w-44 h-14 mt-2"
                    />
                    <div class="space-y-2">
                        <h1 class="text-xl font-bold">
                            {{ company.name }}
                            <div class="w-auto h-px bg-blue-400"></div>
                        </h1>
                        <h2 class="text-xs font-semibold">
                            {{ company.address }}
                        </h2>
                        <h2 class="text-xs font-semibold">
                            {{ company.email }}
                        </h2>
                        <h2 class="text-xs font-semibold">
                            {{ company.phone }}
                        </h2>
                    </div>
                </div>
                <div
                    :class="hiddenClass"
                    class="space-x-3 mt-[4.5rem] print:hidden"
                >
                    <a
                        @click="invoicePrint"
                        class="px-3 py-2 font-semibold text-white bg-gray-600 w-fit h-fit rounded-md cursor-pointer"
                    >
                        <i class="fa-solid fa-print"></i> Invoice Print
                    </a>
                    <a
                        class="px-3 py-2 font-semibold text-white bg-green-600 w-fit h-fit rounded-md cursor-pointer"
                        @click="posPrinter"
                    >
                        <i class="fa-solid fa-print"></i> Pos Print
                    </a>
                    <a
                        href="/sales/list"
                        class="px-3 py-2 font-semibold text-white bg-red-600 w-fit h-fit rounded-md cursor-pointer"
                    >
                        <i class="fa-solid fa-arrow-left"></i> Back
                    </a>
                </div>
            </div>
            <div :class="hiddenClassPos" class="space-x-3 mt-2 print:hidden">
                <a
                    @click="invoicePrint"
                    class="px-3 py-1 text-sm font-semibold text-white bg-gray-600 w-fit h-fit rounded-md cursor-pointer"
                >
                    <i class="fa-solid fa-print"></i> Invoice
                </a>
                <a
                    class="px-3 py-1 text-sm font-semibold text-white bg-green-600 w-fit h-fit rounded-md cursor-pointer"
                    @click="posPrinter"
                >
                    <i class="fa-solid fa-print"></i> Pos
                </a>
                <a
                    class="px-3 py-1 text-sm font-semibold text-white bg-red-600 w-fit h-fit rounded-md cursor-pointer"
                    href="/sales/list"
                >
                    <i class="fa-solid fa-arrow-left"></i> Back
                </a>
            </div>
            <h2
                :class="hiddenClassPos"
                class="text-base font-bold mt-3 pl-[5.5rem] py-2 border-2 mx-auto text-center border-gray-700 border-dotted"
            >
                Invoice
            </h2>
            <div class="flex justify-between" :class="marginTopClass">
                <div>
                    <p class="text-sm font-normal">From</p>
                    <p class="text-sm font-semibold">{{ customer.name }}</p>
                    <p class="text-sm font-normal">{{ customer.address }}</p>
                    <p class="text-sm font-normal">
                        Phone: {{ customer.contact }}
                    </p>
                </div>
                <div :class="hiddenClass">
                    <h2
                        class="text-2xl font-bold mt-3 px-5 py-2 border-2 border-gray-700 border-dotted"
                    >
                        Invoice
                    </h2>
                </div>
                <div class="mt-2 text-right">
                    <p class="text-sm font-semibold">
                        Invoice: {{ sales.code }}
                    </p>
                    <p class="text-sm font-normal">
                        Generated By: {{ sales.created_by.name }}
                    </p>
                    <p class="text-sm font-normal">
                        Generated at: {{ sales.invoice_date }}
                    </p>
                </div>
            </div>
            <div class="mt-5">
                <table class="w-full mt-10">
                    <thead class="w-full">
                        <tr class="shadow-sm border-b-2 border-t-2 w-full">
                            <th class="p-2 text-right w-10">#</th>
                            <th class="p-2 text-right w-20">Particulars</th>
                            <th class="p-2 text-right w-10">Qty</th>
                            <th class="p-2 text-right w-20">Rate</th>
                            <th class="p-2 text-right w-20">Discount</th>
                            <th class="p-2 text-right w-20">Total</th>
                        </tr>
                    </thead>
                    <tbody class="px-2 w-full">
                        <tr
                            v-for="(item, index) in salesDetails"
                            :key="item.id"
                            class="px-3 border-b-2 border-t-2 w-full"
                        >
                            <td class="p-2 text-right">{{ index + 1 }}</td>
                            <td class="p-2 text-right">
                                {{ item.product.name }} <br />
                                {{ item.product_attribute.model }} ::
                                {{ item.product_attribute.size }} ::
                                {{ item.product_attribute.color }}
                            </td>
                            <td class="p-2 text-right">{{ item.qty }}</td>
                            <td class="p-2 text-right">
                                Tk. {{ item.sales_rate }}
                            </td>
                            <td class="p-2 text-right">
                                Tk. {{ item.discount }}
                            </td>
                            <td class="p-2 text-right">Tk. {{ item.total }}</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr class="px-3">
                            <td
                                class="p-2 text-justify"
                                colspan="3"
                                rowspan="3"
                            >
                                <span class="pr-10 text-base font-bold"
                                    >Note:</span
                                >
                                <span class="text-right">{{
                                    sales.note
                                }}</span>
                            </td>
                            <td class="text-right" colspan="3">
                                <span class="pr-10 text-base font-bold"
                                    >Sub total:</span
                                >
                                Tk. {{ sales.total_amount }}
                            </td>
                        </tr>
                        <tr class="px-3">
                            <td class="p-2 text-right" colspan="3">
                                <div class="d-flex justify-content-end">
                                    <div class="pr-10">
                                        <p class="font-bold">Paid Amount:</p>
                                        <p class="text-left font-normal">
                                            {{
                                                salesPayment.transaction_type
                                                    .name
                                            }}
                                        </p>
                                        <p class="font-normal text-left">
                                            {{ salesPayment.created_date }}
                                        </p>
                                    </div>
                                    <p>Tk. {{ sales.paid_amount }}</p>
                                </div>
                            </td>
                        </tr>
                        <tr class="px-3">
                            <td class="p-2 text-right" colspan="3">
                                <span class="pr-10 text-base font-bold"
                                    >Due amount:</span
                                >
                                Tk.
                                {{
                                    sales.total_amount - sales.paid_amount
                                }}
                            </td>
                        </tr>
                        <tr class="px-3">
                            <td class="pt-1 text-left px-2" colspan="3">
                                <span class="text-left font-semibold">
                                    Print Date: {{ print_date }}
                                </span>
                            </td>
                            <td class="pt-1 text-right px-2" colspan="3">
                                <span class="text-left font-semibold">
                                    Paid By : {{ sales.created_by.name }}
                                </span>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</template>

<script>
import { ref } from "vue";
export default {
    setup() {
        var company = ref();
        var customer = ref();
        var sales = ref();
        var salesDetails = ref();
        var hiddenClass = ref();
        var hiddenClassPos = ref("hidden");
        var marginTopClass = ref("mt-5");
        var salesPayment = ref();
        var print_date = moment().format("DD/MM/YYYY");
        var main_content_width = ref("max-width-content");

        const fetchData = () => {
            const URL = window.location.href;
            var sales_id = URL.split("/").reverse()[0];
            axios
                .get(`/sales/invoice/${sales_id}?fetch=true`)
                .then((response) => {
                    sales.value = response.data.data.sales;
                    sales.value.invoice_date = moment(
                        sales.value.invoice_date
                    ).format("DD/MM/YYYY");
                    company.value = sales.value.company;
                    customer.value = sales.value.customer;
                    salesDetails.value = response.data.data.salesDetails;
                    salesPayment.value = response.data.data.salesPayment;
                    salesPayment.value.created_date = moment(
                        sales.value.created_date
                    ).format("DD/MM/YYYY");
                });
        };

        fetchData();

        const invoicePrint = () => {
            main_content_width.value = "max-width-content";
            hiddenClassPos.value = "hidden";
            hiddenClass.value = "flex";
            marginTopClass.value = "mt-5";
            printNow();
        };

        const posPrinter = () => {
            main_content_width.value = "pos-width-content";
            hiddenClass.value = "hidden";
            hiddenClassPos.value = "flex";
            marginTopClass.value = "mt-3";
            printNow();
        };

        const printNow = () => {
            setTimeout(() => {
                window.print();
            }, 300);


        };

        return {
            print_date,
            company,
            customer,
            sales,
            salesPayment,
            hiddenClass,
            hiddenClassPos,
            salesDetails,
            main_content_width,
            marginTopClass,
            invoicePrint,
            posPrinter,
        };
    },
};
</script>

<style></style>
