<template>
    <div class="px-2 sm:px-3 md:px-4 xl:px-5">
        <div class="">
            <h2
                class="text-xl font-bold text-center mt-3 uppercase mx-auto w-fit"
            >
                Payment Slip
                <div class="h-[3px] w-full bg-red-600"></div>
            </h2>
        </div>
        <div class="flex mt-2 space-x-3 justify-between">
            <div class="flex space-x-2">
                <img
                    :src="company.logo"
                    alt="company logo"
                    class="w-44 h-14 mt-2"
                />
                <div class="mt-1">
                    <h1 class="text-xl font-bold">
                        {{ company.name }}
                        <div class="w-auto h-px bg-blue-400"></div>
                    </h1>
                    <h2 class="text-xs font-semibold">
                        {{ company.address }}
                    </h2>
                    <h2 class="text-xs font-semibold">{{ company.email }}</h2>
                    <h2 class="text-xs font-semibold">{{ company.phone }}</h2>
                </div>
            </div>
        </div>
        <div class="flex justify-between mt-2">
            <div>
                <p class="text-sm font-normal">From</p>
                <p class="text-sm font-semibold">{{ customer.name }}</p>
                <p class="text-sm font-normal">{{ customer.address }}</p>
                <p class="text-sm font-normal">Phone: {{ customer.contact }}</p>
            </div>
            <div>
                <p class="text-sm font-semibold">
                    Receipt No: {{ salesPayment.receipt_no }}
                </p>
                <p class="text-sm font-normal">
                    Generated By: {{ salesPayment.added_by.name }}
                </p>
                <div class="d-flex justify-content-end">
                    <div class="pr-10">
                        <p class="font-bold">Paid Amount:</p>
                        <p class="text-left font-normal">
                            {{ salesPayment.transaction_type.name }}
                        </p>
                        <p class="font-normal text-left">
                            {{ salesPayment.created_date }}
                        </p>
                    </div>
                    <p>Tk. {{ salesPayment.amount }}</p>
                </div>
                <span class="text-left font-semibold">
                    Paid By : {{ salesPayment.added_by.name }}
                </span>
            </div>
        </div>
    </div>
</template>

<script>
import { ref, toRefs } from "vue";
export default {
    props: {
        data: {
            type: Object,
            required: true,
        },
    },

    setup(props) {
        const { data } = toRefs(props);

        var company = ref();
        var customer = ref();
        var sales = ref();
        var salesPayment = ref();
        var salesDetails = ref();

        const fetchData = () => {
            console.log(data.value);
            salesPayment.value = data.value;
            company.value = data.value.added_by.company;
            customer.value = data.value.customer;
        };

        fetchData();

        setTimeout(() => {
            window.print();
        }, 1000);


        // check window is open or closed
        window.onafterprint = function () {
            window.location.href = "/sales/payment-list";
        };

        return {
            company,
            customer,
            sales,
            salesPayment,
            salesDetails,
        };
    },
};
</script>

<style></style>
